import Image from 'next/image'
import '../shared/css/globalStyles.css'
import Github from '@/public/icons/Github.svg'
import ShelfModal from '@/features/shelf/ui/create-modal'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className=' bg-black'>
				<header className='flex mt-11 items-center justify-between'>
					<div className='flex items-center'>
						<Image alt='Github' src={Github} width={43} height={43} />
						<div className='ml-2 text-gray-500'>
							<div className='font-medium text-lg leading-tight text-white'>
								Browser Home
							</div>
							<div>
								by
								<a href='https://github.com/FLEYreal'> FLEYreal</a> &{' '}
								<a href='https://github.com/avariceJS'>AvariceJS</a>
							</div>
						</div>
					</div>
					<div>
						<ShelfModal variant='create'></ShelfModal>
					</div>
				</header>
				{children}
			</body>
		</html>
	)
}
