"""Add icon_ext column

Revision ID: 0190cf4b5a43
Revises: 41db7219233a
Create Date: 2024-01-25 13:27:34.261862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0190cf4b5a43'
down_revision: Union[str, None] = '41db7219233a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('icon_ext', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'icon_ext')
    # ### end Alembic commands ###
