"""Add new column specifically for svg

Revision ID: 20d10c91098d
Revises: 0190cf4b5a43
Create Date: 2024-01-25 13:55:58.368651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d10c91098d'
down_revision: Union[str, None] = '0190cf4b5a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('icon_svg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'icon_svg')
    # ### end Alembic commands ###
