"""link row added, description is nullable

Revision ID: 36bd37c651b7
Revises: 23115d87556f
Create Date: 2024-01-22 15:21:28.978417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bd37c651b7'
down_revision: Union[str, None] = '23115d87556f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('link', sa.String(), nullable=False))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('items', 'link')
    # ### end Alembic commands ###
