"""shelf_fk cannot be null

Revision ID: ffe1210170e4
Revises: 20d10c91098d
Create Date: 2024-01-27 15:17:45.345744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe1210170e4'
down_revision: Union[str, None] = '20d10c91098d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'shelf_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'shelf_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
